name: Build with No Donation

on:
  workflow_dispatch:

permissions:
  contents: write  # يمنح إذن الكتابة لدفع التعديلات

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

      - name: Clone XMRig Repository
        run: git clone https://github.com/xmrig/xmrig.git

      - name: Modify donate.h to Disable Donation
        run: |
          sed -i 's/constexpr const int kDefaultDonateLevel = 1;/constexpr const int kDefaultDonateLevel = 0;/' xmrig/src/donate.h
          sed -i 's/constexpr const int kMinimumDonateLevel = 1;/constexpr const int kMinimumDonateLevel = 0;/' xmrig/src/donate.h

      - name: Build XMRig
        run: |
          cd xmrig
          mkdir build && cd build
          cmake .. -DWITH_HWLOC=ON -DWITH_OPENCL=OFF -DWITH_CUDA=OFF -DCMAKE_BUILD_TYPE=Release -DXMRIG_DEPS=scripts/deps -DDONATE_LEVEL=0
          make -j$(nproc)

      - name: Commit and Push Built Binary to Repository
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # استخدام التوكن من Secrets
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mkdir -p release
          cp xmrig/build/xmrig release/
          cd release
          git init
          git remote add origin https://x-access-token:${GH_PAT}@github.com/Solomon26014226/clonex.git
          git add .
          git commit -m "Add modified XMRig binary with no donation"
          git branch -M main
          git push -f origin main
          
