name: Check macOS Capabilities

on:
  workflow_dispatch:

jobs:
  check-capabilities:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check system information
      run: |
        echo "System Information:"
        system_profiler SPSoftwareDataType
        echo "Hardware Information:"
        system_profiler SPHardwareDataType
        echo "Network Information:"
        system_profiler SPNetworkDataType
        echo "Storage Information:"
        system_profiler SPStorageDataType