name: Test System Features

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-system:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y msr-tools

      - name: Enable Huge Pages
        run: |
          echo 1280 | sudo tee /proc/sys/vm/nr_hugepages
          sudo sysctl -w vm.nr_hugepages=1280
          sudo sysctl -w vm.hugetlb_shm_group=$(id -g)

      - name: Check Huge Pages Status
        run: cat /proc/meminfo | grep Huge

      - name: Check MSR Access
        run: |
          sudo modprobe msr
          ls /dev/cpu/*/msr || echo "MSR access is not available"

      - name: Try MSR Tweaks
        run: |
          sudo chmod 777 /dev/cpu/*/msr
          sudo wrmsr -a 0xc0011020 0 || echo "Failed to write MSR 0xc0011020"
          sudo wrmsr -a 0xc0011021 0x40 || echo "Failed to write MSR 0xc0011021"
          sudo wrmsr -a 0xc0011022 0x15151515 || echo "Failed to write MSR 0xc0011022"
          sudo wrmsr -a 0xc001102b 0x2000030000000000 || echo "Failed to write MSR 0xc001102b"
